#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    Apr 23, 2015 04:15:17 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans} -size 10 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {DejaVu Sans} -size 24 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+666+298
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1665 1020
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    message $top.mes38 \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font10,object) \
        -foreground {#000000} -highlightcolor black \
        -text {首先确保完全解压全部文件。

然后请输入你希望默写的list数字(1-31)，如1,2,3,使用逗号分隔，随后点击RUN按钮。

程序会生成相应的txt文件，你可以在word或者任何编辑器中打开。

文件分成两个，一个是英文(随机乱序)，一个是对应的中文解释。


有问题请联系:iphyer@163.com或者微博：日月人依依} \
        -width 385 
    vTcl:DefineAlias "$top.mes38" "Message1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent39 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent39" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font11,object) \
        -foreground {#000000} -highlightcolor black -text 再要你命3000默写程序 
    vTcl:DefineAlias "$top.lab40" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command {def Button1Click(p1):
    sys.exit()} \
        -foreground {#000000} -highlightcolor black -text RUN 
    vTcl:DefineAlias "$top.but45" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $top.cpd38 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -command {def Button1Click(p1):
    sys.exit()} \
        -foreground {#000000} -highlightcolor black -text EXIT 
    vTcl:DefineAlias "$top.cpd38" "Button2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.mes38 \
        -in $top -x 130 -y 160 -width 385 -height 263 -anchor nw \
        -bordermode ignore 
    place $top.ent39 \
        -in $top -x 180 -y 100 -width 246 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab40 \
        -in $top -x 130 -y 20 -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 230 -y 150 -anchor nw -bordermode ignore 
    place $top.cpd38 \
        -in $top -x 310 -y 150 -anchor nw -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

