#! /usr/bin/env python
# coding=utf-8
# GUI module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Apr 23, 2015 04:15:22 PM
import sys
import sqlite3
import io
import tkMessageBox

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import ZYNM3k_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('再要你命3默写程序2.0')
    geom = "600x450+667+322"
    root.geometry(geom)
    w = New_Toplevel_1 (root)
    ZYNM3k_support.init(root, w)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('再要你命3默写程序2.0')
    geom = "600x450+667+322"
    w.geometry(geom)
    w_win = New_Toplevel_1 (w)
    ZYNM3k_support.init(w, w_win, param)
    return w_win

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {DejaVu Sans} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font11 = "-family {DejaVu Sans} -size 24 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        master.configure(highlightcolor="black")


        self.Message1 = Message(master)
        self.Message1.place(relx=0.22, rely=0.36, relheight=0.58, relwidth=0.65)
        self.Message1.configure(font=font10)
        self.Message1.configure(text='''首先确保完全解压全部文件。

然后请输入你希望默写的list数字(1-31)，如1,2,3,使用逗号分隔，随后点击RUN按钮。

程序会生成相应的txt文件你可以在word或者任何编辑器中打开。

文件分成两个，一个是英文(随机乱序)，一个是对应的中文解释。

有问题请联系:iphyer@163.com,或者微博at：日月人依依''')
        self.Message1.configure(width=385)
        
        self.Entry1 = Entry(master)
        self.Entry1.place(relx=0.3, rely=0.22, relheight=0.05, relwidth=0.41)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(selectbackground="#c4c4c4")

        self.Label1 = Label(master)
        self.Label1.place(relx=0.22, rely=0.04, height=42, width=380)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(font=font11)
        self.Label1.configure(text='''再要你命3默写程序2.0''')

        self.Button1 = Button(master)
        self.Button1.place(relx=0.30, rely=0.33, height=27, width=52)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''RUN''')
        self.Button1.configure(command=self.generate_txt)

        self.Button2 = Button(master)
        self.Button2.place(relx=0.60, rely=0.33, height=27, width=53)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(text='''EXIT''')
        self.Button2.configure(command=sys.exit)
        
        
    def generate_txt(self):
        s = self.Entry1.get()
        sql=input_reforming(s)
        conn = sqlite3.connect('3k.sqlite')
        print "Opened database successfully";
        cu = conn.cursor()
        cu.execute(sql)
        rows = cu.fetchall()
        writefile(rows)
        print 'Done'
        tkMessageBox.showinfo("完成", "完成")
        
   
    
        
def input_reforming(s):
    a=s.split(',')
    sql_begin="SELECT Column1 AS Eng,Column2 AS Chn, random() AS r FROM list"
    sql_repeat=" UNION ALL SELECT Column1 AS Eng,Column2 AS Chn, random() AS r FROM list"
    sql_last=" ORDER BY r"
    
    for i in range(0,len(a)):
        if i == 0:
            sql_whole=sql_begin+a[i]
        else:
            sql_whole=sql_whole+sql_repeat+a[i]
    
    sql_whole=sql_whole+sql_last
    return sql_whole

def writefile(rows):
    file_eng= io.open ("Eng.txt","w+",encoding='utf8')
    file_chn= io.open ("Chn.txt","w+",encoding='utf8')
    for row in rows:
        file_eng.write("%s  \n" % row[0])
        file_chn.write("%s  \n" % row[1])
    file_eng.close()
    file_chn.close()


   






if __name__ == '__main__':
    vp_start_gui()



